/** motonui domain types — AI and Tiptap document types. */

// =============================================================================
// AI TYPES
// =============================================================================

/** Result of AI caption generation */
export interface CaptionResult {
  caption: string;          // 150-200 chars for carousel / 50-80 for story
  captionLong?: string;     // 400-600 chars for blog
  hashtags: string[];       // 30 suggested tags (without '#')
  altText?: string;         // accessibility description
}

/** SEO metadata generated by AI */
export interface SEOMetadata {
  seoTitle: string;         // max 60 chars
  seoDescription: string;   // max 160 chars
  ogDescription: string;
  slug: string;
  focusKeyphrase: string;
}

/** Destination briefing from AI research */
export interface DestinationBriefing {
  summary: string;
  bestTimeToVisit: string;
  mustSee: string[];
  localTips: string[];
  currencyTip: string;
  languageTip: string;
}

/** Context passed to the blog AI assistant */
export interface TripContext {
  tripName: string;
  destination: string;
  startDate: string;
  endDate: string;
  memberNames: string[];
}

// =============================================================================
// TIPTAP DOCUMENT TYPES
// =============================================================================

export interface TiptapDoc {
  type: 'doc';
  content: TiptapNode[];
}

export interface TiptapNode {
  type: string;
  attrs?: Record<string, unknown>;
  content?: TiptapNode[];
  marks?: TiptapMark[];
  text?: string;
}

export interface TiptapMark {
  type: string;
  attrs?: Record<string, unknown>;
}
